# Numpy Array
- Faster then pure array in python when opetarion it

In [ ]:
import numpy as np
from timeit import Timer

In [ ]:
size_of_vec = 10000 
list1 = range(size_of_vec)
list2 = range(size_of_vec)
nmpy1 = np.arange(size_of_vec)
nmpy2 = np.arange(size_of_vec)

In [ ]:
def sum_array():
  tmp = []
  for i in range(len(list1)):
    tmp.append(list1[i]+list2[i])
  return tmp

def sum_np():
  return nmpy1 + nmpy2

In [ ]:
arr1 = Timer("sum_array()", "from __main__ import sum_array")
arr2 = Timer("sum_np()", "from __main__ import sum_np")

In [ ]:
print("pyton version: ", arr1.timeit(1000))
print("numpy version: ", arr2.timeit(1000))

pyton version:  3.3083204260001366
numpy version:  0.0058217790010530734


In [ ]:
#numpy five even number
np.array([x for x in range(1,10) if x % 2 == 1])

array([1, 3, 5, 7, 9])

In [ ]:
np_array_1 = np.array([[1,2],
          [3,4],
          [5,6]])

In [ ]:
#the number of elements in array
print("size: ", np_array_1.size)
#check the datatype of the array
print("datatype: ", np_array_1.dtype)
#check the shape (rows x col)
print("shape: ", np_array_1.shape)
#check array dimension
print("dimension: ", np_array_1.ndim)


size:  6
datatype:  int64
shape:  (3, 2)
dimension:  2


### Create numpy array

In [ ]:
#1
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
#range number
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#null value
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [ ]:
#one value
arr4 = np.ones(5)
arr4

array([1., 1., 1., 1., 1.])

In [ ]:
#generate value from range x - y, and howmuch element inside the range, default num value is 50
arr5 = np.linspace(start = 1, stop= 100, num=11)
arr5

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

### add, remove, sort, reshape, indexing and striding
indexing:<br>
positive : row and colum start from 0<br>
negative : start from -1, the last row index is -1 <br>
striding : read an ndarray but, with skip row

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
#add element 
#numpy doesn support array_name.append(val) 
arr1 = np.append(arr1, 6)
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
#remove element by index 
arr1 = np.delete(arr1, 4) #can also implemented in list
arr1

array([1, 2, 3, 4, 6])

In [ ]:
#sorting
arrx = np.array([4,7,2,5,4,2])
asc = np.sort(arrx)
desc = -np.sort(-arrx) #sort negative value * negative
print(asc)
print(desc)

[2 2 4 4 5 7]
[7 5 4 4 2 2]


In [ ]:
#reshape, note the number of element = resape1*resape2
#can also implemented in pure list
arr = np.arange(2,50,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
np.reshape(arr,(6,4))

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
arr.reshape(3,8)

array([[ 2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44, 46, 48]])

In [ ]:
#slicing
arr3D = arr.reshape(3,8)

In [ ]:
#positive slicing
arr3D[1,2]

22

In [ ]:
arr3D[0:2, 2:5] #rows 1,2 and col 2,3,4

array([[ 6,  8, 10],
       [22, 24, 26]])

In [ ]:
#negative slicing get number 10
arr3D[-3, -4]

10

In [ ]:
#get same value with positive slicing
arr3D[-3:-1, -6:-3]

array([[ 6,  8, 10],
       [22, 24, 26]])

In [ ]:
#striding
arr6D = np.reshape(arr,(6,4))
arr6D

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
arr6D[0:6:2]

array([[ 2,  4,  6,  8],
       [18, 20, 22, 24],
       [34, 36, 38, 40]])

In [ ]:
test = np.arange(0,25)
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
test = test.reshape(5,5)
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
test[0:2, 3:]

array([[3, 4],
       [8, 9]])

In [ ]:
test[1:5:2,0:5:2] #even colum and odd rows

array([[ 5,  7,  9],
       [15, 17, 19]])

#Pandas
There are 2 types data in pandas : series and dataframe<br>
- series is 1 dimensinal array with label
- 2D table, collection of Series, structured with labeled

### Dataframe and Series

In [ ]:
import pandas as pd

In [ ]:
number = pd.Series([1,2,3,4,5])
number

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#get number values
number.values
#get detail index series
number.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#Series from dictionary
book_stock = {"Bi": 5, "IPA": 10, "MTK": 7, "English":9}
pd.Series(book_stock)

Bi          5
IPA        10
MTK         7
English     9
dtype: int64

In [ ]:
book = pd.Series(book_stock)
book["Bi"]

5

In [ ]:
#DataFrame
students = [[101, "Mohamad", 80],
            [102, "Irwan", 75],
            [103, "Afandi", 85]]
pd.DataFrame(students, columns=["No", "Name", "Score"], index=[x+1 for x in range(len(students))])

No     Name  Score
1  101  Mohamad     80
2  102    Irwan     75
3  103   Afandi     85

In [ ]:
"""
Create dataframe from dictionary, keys as column name and values as value
If the dictionary with single value (not an array), we need add index when creating dataframe
"""

pd.DataFrame(book_stock, index=[0])

Bi  IPA  MTK  English
0   5   10    7        9

### Read and write csv file

In [ ]:
df = pd.read_csv("final_dataset_basicmlmodel.csv")
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
from google.colab import files

new_data = df.iloc[0:3, 1:]
new_data.to_csv("new_data.csv")
files.download('new_data.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Method in pandas

In [ ]:
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
df.head(3)

In [ ]:
df.tail()

In [ ]:
df.tail(2)

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.shape

### indexing, selecting and assigning

Indexing<br>
- iloc : index based selection (selecting data based in numerical position)
- loc  : label based selection (selecting data based on the column or row name/index )

In [ ]:
df = pd.read_csv("exam_scores - exam_scores.csv")
df.head()

gender race/ethnicity  ... reading score writing score
0    male        group B  ...            68            67
1  female        group C  ...            68            66
2    male        group C  ...            65            65
3  female        group D  ...            75            73
4    male        group D  ...            77            71

[5 rows x 8 columns]

In [ ]:
df.iloc[0]
# df.iloc[0][5] #get just math score

gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    74
reading score                                 68
writing score                                 67
Name: 0, dtype: object

In [ ]:
#get students score for every subject [row_start:row_end, col_start:col_end]
df.iloc[0:10, 5:] #first ten students

math score  reading score  writing score
0          74             68             67
1          58             68             66
2          66             65             65
3          74             75             73
4          78             77             71
5          75             82             85
6          69             78             80
7          54             50             48
8          65             58             55
9          87             75             79

In [ ]:
#loc : [start:end(end index include), [columns]]
df.loc[0:5, ["math score", "reading score", "writing score"]]

math score  reading score  writing score
0          74             68             67
1          58             68             66
2          66             65             65
3          74             75             73
4          78             77             71
5          75             82             85

In [ ]:
#different between loc and iloc
a = pd.Series([10,20,30,40,50], index=[1,3,5,9,11])

In [ ]:
#loc based on the real index value
a.loc[1]

10

In [ ]:
#iloc based on index position, so not depends on index value
a.iloc[0]

10

Selecting

In [ ]:
#selecting column
df[["gender", "lunch", "test preparation course"]].head(2)

gender     lunch test preparation course
0    male  standard                    none
1  female  standard               completed

In [ ]:
df[df["math score"]>=98]

gender race/ethnicity  ... reading score writing score
91     male        group D  ...            94            96
128    male        group A  ...            97            94
495    male        group C  ...            96           100
565    male        group E  ...           100           100
588    male        group D  ...            85            91
620    male        group E  ...            87            78
744  female        group E  ...           100           100
776    male        group E  ...           100           100
844  female        group E  ...            95            92
911    male        group E  ...            95            87
996  female        group E  ...            81            94

[11 rows x 8 columns]

Assign

In [ ]:
df.loc[df["math score"]<=25,["math score"]]

math score
349          25
739          25
854          18
891          23
949          15

In [ ]:
dfx = df.copy()
dfx.loc[dfx["math score"]<=25,["math score"]] = 30 #assign
dfx.loc[dfx["math score"]<=30,["math score"]]

math score
310          30
316          28
349          30
739          30
854          30
891          30
949          30

In [ ]:
sma_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")

In [ ]:
sma_data.head()

land_area  percent_city  percent_senior  ...  income  region  crime_rate
0       1384          78.1            12.3  ...   72100       1       75.55
1       3719          43.9             9.4  ...   54542       2       56.03
2       3553          37.4            10.7  ...   33216       1       41.32
3       3916          29.9             8.8  ...   32906       2       67.38
4       2480          31.5            10.5  ...   26573       4       80.19

[5 rows x 10 columns]

In [ ]:
sma_data.tail(1)

land_area  percent_city  percent_senior  ...  income  region  crime_rate
98        654          28.8             3.9  ...    1148       3       68.76

[1 rows x 10 columns]

In [ ]:
sma_data.loc[[1, 3, 5, 7, 9, 13], ['land_area', 'work_force', 'income', 'region', 'crime_rate']]

land_area  work_force  income  region  crime_rate
1        3719      3305.9   54542       2       56.03
3        3916      1966.7   32906       2       67.38
5        2815      1541.9   25663       3       58.48
7        6794      1272.7   18221       3       64.88
9        4647      1032.2   14542       2       55.30
13        782       915.2   12591       4       63.20

In [ ]:
sma_data[sma_data["region"]==2].reset_index()

index  land_area  percent_city  ...  income  region  crime_rate
0       1       3719          43.9  ...   54542       2       56.03
1       3       3916          29.9  ...   32906       2       67.38
2       9       4647          31.5  ...   14542       2       55.30
3      11       1519          31.8  ...   14684       2       52.73
4      15       1456          46.7  ...   10104       2       44.64
5      17       2149          29.8  ...    9037       2       49.69
6      19       3341          35.8  ...    9106       2       63.04
7      21       3072          68.0  ...    7736       2       53.65
8      23       2460          49.6  ...    6658       2       57.59
9      29       2187          47.0  ...    5142       2       59.48
10     35        903          37.3  ...    4102       2       52.53
11     37        938          48.1  ...    4177       2       54.51
12     44       1537          63.8  ...    3725       2       55.54
13     45       1420          32.6  ...    3553       2       46.26
14     48       1182          32.4  ...    3627       2       68.48
15     56       2277          39.5  ...    2853       2       44.07
16     61       2449          68.4  ...    2651       2       63.67
17     64       1704          52.1  ...    2662       2       49.60
18     65       1750          49.3  ...    2439       2       44.67
19     71       1136          58.6  ...    2396       2       61.46
20     82       1975          46.5  ...    1853       2       43.94
21     83       1404          38.5  ...    1776       2       40.54
22     87       7397          47.3  ...    1654       2       45.97
23     91        711          42.4  ...    1790       2       64.91
24     92        471          46.3  ...    1458       2       53.68

[25 rows x 11 columns]

### Summary

In [ ]:
#for default, just show the numerical value
df.describe()

math score  reading score  writing score
count  1000.000000     1000.00000    1000.000000
mean     67.128000       70.17400      68.973000
std      14.815367       14.85599      15.109155
min      15.000000       18.00000      10.000000
25%      58.000000       60.00000      59.000000
50%      67.000000       70.00000      69.000000
75%      78.000000       81.00000      80.000000
max     100.000000      100.00000     100.000000

In [ ]:
#summary of categorical columns
df.describe(include='object')

gender race/ethnicity  ...     lunch test preparation course
count     1000           1000  ...      1000                    1000
unique       2              5  ...         2                       2
top     female        group C  ...  standard                    none
freq       502            294  ...       649                     654

[4 rows x 5 columns]

In [ ]:
#all summary
df.describe(include='all')

gender race/ethnicity  ... reading score writing score
count     1000           1000  ...    1000.00000   1000.000000
unique       2              5  ...           NaN           NaN
top     female        group C  ...           NaN           NaN
freq       502            294  ...           NaN           NaN
mean       NaN            NaN  ...      70.17400     68.973000
std        NaN            NaN  ...      14.85599     15.109155
min        NaN            NaN  ...      18.00000     10.000000
25%        NaN            NaN  ...      60.00000     59.000000
50%        NaN            NaN  ...      70.00000     69.000000
75%        NaN            NaN  ...      81.00000     80.000000
max        NaN            NaN  ...     100.00000    100.000000

[11 rows x 8 columns]

### Aggregation Function

In [ ]:
df["math score"].mean()

67.128

In [ ]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df["writing score"].max()

100

In [ ]:
df["gender"].value_counts()

female    502
male      498
Name: gender, dtype: int64

### Sorting and renaming

In [ ]:
#sorting
df.sort_values(by="math score", ascending=False, ignore_index=True)[0:10]

gender race/ethnicity  ... reading score writing score
0    male        group D  ...            94            96
1    male        group E  ...           100           100
2    male        group D  ...            85            91
3    male        group A  ...            97            94
4    male        group E  ...           100           100
5    male        group E  ...            95            87
6    male        group C  ...            96           100
7    male        group E  ...            87            78
8  female        group E  ...            95            92
9  female        group E  ...           100           100

[10 rows x 8 columns]

In [ ]:
#rename column
df.rename(columns={'race/ethnicity':'race', 'parental level of education':'education_level',
                   'test preparation course':'course_status', 'math score':'math',
                   'writing score':'writing', 'reading score':'reading'}, inplace=True)

In [ ]:
df.head()

gender     race    education_level  ... math reading  writing
0    male  group B  bachelor's degree  ...   74      68       67
1  female  group C       some college  ...   58      68       66
2    male  group C       some college  ...   66      65       65
3  female  group D  bachelor's degree  ...   74      75       73
4    male  group D       some college  ...   78      77       71

[5 rows x 8 columns]

In [ ]:
#get columns list
df.columns

Index(['gender', 'race', 'education_level', 'lunch', 'course_status', 'math',
       'reading', 'writing'],
      dtype='object')

In [ ]:
#rename index
df.rename(index={0:'zero', 3:'three'}).head(4)

gender     race    education_level  ... math reading  writing
zero     male  group B  bachelor's degree  ...   74      68       67
1      female  group C       some college  ...   58      68       66
2        male  group C       some college  ...   66      65       65
three  female  group D  bachelor's degree  ...   74      75       73

[4 rows x 8 columns]

### Missing Data and How to Handle It
- isnull/isna : check the null value
- notnull : check not null value
- dropna : return df without missing value (drop all missing value, axis 0 is rows and axis 1 is columns). Inside the method you can add parameter how='all', to drop rows/column where all the data is null. You can add tresh method, how much missing value allow in the data.
- fillna : replace the missing value by another value, add method ffill/bfill with axis 1/0
- interpolate : df.interploate(methode='time'), this method will fill the missing value by new value where it near with  the nearst date. For ex: null value at 23 July, this data between 20 July and 24July. So the new value will near with  value in 24 july. You can change the method

In [ ]:
#isna or isnull are equal
df.isnull().sum()

gender             0
race               0
education_level    0
lunch              0
course_status      0
math               0
reading            0
writing            0
dtype: int64

In [ ]:
df.columns.to_list()

['gender',
 'race',
 'education_level',
 'lunch',
 'course_status',
 'math',
 'reading',
 'writing']

In [ ]:
import numpy as np
df2 = pd.DataFrame(["male", "group D", "some college", np.nan, np.nan, 80, 90, np.nan])
df2 = df2.T
df2

0        1             2    3    4   5   6    7
0  male  group D  some college  NaN  NaN  80  90  NaN

In [ ]:

df2.rename(columns={0:'gender', 1:'race', 2:'education_level', 3:'lunch', 4:'course_status', 
                    5:'math', 6:'reading', 7:'writing'}, inplace=True)
df2

gender     race education_level lunch course_status math reading writing
0   male  group D    some college   NaN           NaN   80      90     NaN

In [ ]:
df = df.append(df2, ignore_index=True)
df.isnull().sum()

gender             0
race               0
education_level    0
lunch              2
course_status      2
math               0
reading            0
writing            2
dtype: int64

In [ ]:
df.tail()

gender     race     education_level  ... math reading writing
997   female  group E  associate's degree  ...   67      67      67
998   female  group C         high school  ...   63      68      70
999     male  group C        some college  ...   49      57      50
1000    male  group D        some college  ...   80      90     NaN
1001    male  group D        some college  ...   80      90     NaN

[5 rows x 8 columns]

In [ ]:
#fill using text
df.course_status.fillna('unknown', inplace=True)

In [ ]:
df.writing.fillna(df.writing.mean(), inplace=True)

In [ ]:
#fill( forward fill, value before that data), bfill (backword fill, value after that data)
df.lunch.fillna(method='ffill', inplace = True)

In [ ]:
df.tail()

gender     race     education_level  ... math reading writing
997   female  group E  associate's degree  ...   67      67  67.000
998   female  group C         high school  ...   63      68  70.000
999     male  group C        some college  ...   49      57  50.000
1000    male  group D        some college  ...   80      90  68.973
1001    male  group D        some college  ...   80      90  68.973

[5 rows x 8 columns]

In [ ]:
df.isnull().sum()

gender             0
race               0
education_level    0
lunch              0
course_status      0
math               0
reading            0
writing            0
dtype: int64

In [ ]:
#case
titanic_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/First_ML_Model/master/titanic.csv')

In [ ]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
titanic_data.Age.fillna(titanic_data.Age.mean(), inplace=True)

In [ ]:
titanic_data.Age.mean()

29.699117647058763

In [ ]:
titanic_data.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
titanic_data.Embarked.mode()

0    S
dtype: object

In [ ]:
titanic_data.Embarked.fillna(titanic_data.Embarked.mode()[0], inplace=True)

In [ ]:
titanic_data.Embarked.value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

### Pandas Striang Operation

In [ ]:
#but if null value axis in the array, it gonna be error
data = ["MOHAMAD", "Irwan", "afandi", "sayID", "RasYId"]
[val.capitalize() for val in data] #list comprehension

['Mohamad', 'Irwan', 'Afandi', 'Sayid', 'Rasyid']

In [ ]:
name = pd.Series(["Lapoerta MOtanu", "IHSAN Gondozue", "MISKA MELISA", "MIKa Aguero", "Zach MATERAZI"])

In [ ]:
name.str.lower()

0    lapoerta motanu
1     ihsan gondozue
2       miska melisa
3        mika aguero
4      zach materazi
dtype: object

In [ ]:
name.str.len()

0    15
1    14
2    12
3    11
4    13
dtype: int64

In [ ]:
name.str.startswith("L")

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
name = name.str.lower()
name.str.split()

0    [lapoerta, motanu]
1     [ihsan, gondozue]
2       [miska, melisa]
3        [mika, aguero]
4      [zach, materazi]
dtype: object

### Concat and Append

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4,5,6])
pd.concat([ser1, ser2]) #defaul axis 0, mean rows

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object